* File: nand.pex.netlist.NAND.pxi
* Created: Fri May 18 17:19:54 2018
* 
x_PM_NAND%X N_X_M0_g N_X_M2_g X PM_NAND%X
x_PM_NAND%GND! N_GND!_M0_b N_GND!_M0_s GND! PM_NAND%GND!
x_PM_NAND%3 N_3_M0_d N_3_M1_s PM_NAND%3
x_PM_NAND%Y N_Y_M1_g N_Y_M3_g Y PM_NAND%Y
x_PM_NAND%VOUT VOUT N_VOUT_M2_d N_VOUT_M3_s N_VOUT_M1_d PM_NAND%VOUT
x_PM_NAND%VDD! VDD! N_VDD!_M2_b N_VDD!_M2_s N_VDD!_M3_d PM_NAND%VDD!
